# Generated by Django 2.0 on 2020-07-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.IntegerField(default=0)),
                ('raw_text', models.CharField(max_length=200)),
                ('blob_id', models.IntegerField(default=0)),
                ('blob_url', models.CharField(max_length=200)),
                ('nice_filename', models.CharField(max_length=200)),
                ('nice_path', models.CharField(max_length=200)),
                ('local_path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
