# Generated by Django 2.2.14 on 2020-07-24 20:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth0login', '0002_auto_20200722_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.IntegerField(default=0)),
                ('tag_de', models.CharField(max_length=200)),
                ('tag_en', models.CharField(max_length=200)),
                ('tag_fr', models.CharField(max_length=200)),
                ('tag_es', models.CharField(max_length=200)),
                ('tag_it', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(default=0)),
                ('event_subtype', models.IntegerField(default=0)),
                ('event_details', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
